### ISSUE TITLE
Failing deployment

### ISSUE THREAD

**Issue by 7770x** [NexusMutual/smart-contracts#133]
Hey guys, wanted to try deploying your contract onto kovan, but keep running into this exception:

```
Deploying proxy DisposableMemberRoles
An unexpected error encountered: Error: Returned error: The execution failed due to an exception.
    at deployProxy (/smart-contracts/scripts/deploy.js:99:46)
    at main (/smart-contracts/scripts/deploy.js:159:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  data: {
    stack: 'ProviderError: The execution failed due to an exception.\n' +
      '    at HttpProvider.request (/smart-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)\n' +
      '    at LocalAccountsProvider.request (/smart-contracts/node_modules/hardhat/src/internal/core/providers/accounts.ts:168:34)\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
      '    at AutomaticGasProvider._getMultipliedGasEstimation (/smart-contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:72:31)\n' +
      '    at AutomaticGasProvider.request (/smart-contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:131:18)\n' +
      '    at Web3HTTPProviderAdapter._sendJsonRpcRequest (/smart-contracts/node_modules/@nomiclabs/hardhat-web3/src/web3-provider-adapter.ts:80:22)',
    name: 'ProviderError'
  },
  hijackedStack: 'Error: Returned error: The execution failed due to an exception.\n' +
    '    at Object.ErrorResponse (/smart-contracts/node_modules/web3-core-requestmanager/node_modules/web3-core-helpers/lib/errors.js:28:19)\n' +
    '    at /smart-contracts/node_modules/web3-core-requestmanager/lib/index.js:303:36\n' +
    '    at cb (util.js:289:31)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:82:21)'
}
```
Looks like the DisposableMemberRoles contract is running into some error, but not clear how to fix it

**Comment by shark0der** [comment]
Closing due to inactivity. Feel free to reopen if you still experience the issue.
